theme = "catppuccin_frappe"
[editor]
auto-format = true
line-number = "relative"
scrolloff.vertical = 999
rulers = [80]

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
display-messages = true

[keys.normal."+"]
s = ":sh git status"
l = ":sh git log --graph --abbrev-commit --format='%C(blue)%h%C(reset) %C(yellow)%d%C(reset) %s - %C(green)(%cr)[%an]%C(reset)'"
