
[[language]]
auto-format = true
name = "rust"

[[language]]
auto-format = true
name = "nix"

[language.formatter]
command = "nixpkgs-fmt"

[[language]]
language-servers = ["ltex-ls", "marksman"]
name = "markdown"
text-width = 80

[language.soft-wrap]
enable = true

[language-server.ltexplus]
command = "$HOME/Downloads/ltex-ls-plus-18.4.0/bin/ltex-ls-plus"

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType", outputPath = "$root/target/$dir/$name" }

[language-server.typstspell]
command = "typst-languagetool-lsp"
config = {backend = "bundle", main = "main.typ", languages = {de = "de-DE", en = "en-US"}, on_change = "200ms"}

[[language]]
name = "typst"
language-servers = ["tinymist", "typstspell"]
